### PR TITLE
Fix FIFO path on newer Weechat versions.

### LINKED ISSUE #1: Inwee breaks on Weechat 1.7
As of Weechat 1.7 (more specifically, [this][wcmt] commit), the `%h/.weechat/weechat_fifo_{PID}` path no longer exists. In fact, it can now be custom defined by the user in the `fifo.conf` file.

My proposal to fix this is to try the PID version of the FIFO socket first, if that fails, fail **silently**, and then try the path `%h/.weechat/weechat_fifo`, and if that fails, then pass on a error message.

Inwee should also allow a parameter to accept a custom path to the FIFO socket.

Thanks!

[wcmt]: https://git.io/vMyfh

### PR DESCRIPTION
**Pull request by shymega**
This PR fixes #1, and implements systematic tries of the Weechat FIFO path, as described in commit df0af77 and updates the README to reflect that.

### CODE REVIEW

**Comment by susam** [comment]
@shymega Thanks for sending this pull request. I appreciate the care with which you have written the changes with detailed comments and additional debug output messages. Also special thanks for updating the README as well.

I have the following request for changes.

1. Please change `-fp` and `--fifo-path` to `-f` and `--fifo`. This is going to be more consistent with the existing option names that are quite short.
2. I don't think an additional block of code is required for finding version 1.7 fifo. If you just change

        for f in ~/.weechat/weechat_fifo_*

   to the following, it should work fine for both version 1.7 and older versions.

        for f in ~/.weechat/weechat_fifo*

Please let me know if you can make these changes. I understand if you don't have the time to make additional changes. In that case, I will merge your pull request and make the changes myself later.

**Comment by shymega** [comment]
Hi there!

I've made these changes to the PR. Let me know how it seems to you- I've run it locally, and it appears to work.

**Comment by susam** [comment]
Thanks for the changes. I have merged this pull request to master. The changes are now available in version 0.2.0. I don't know why GitHub did not close this pull request automatically. I have raised a support request to enquire about it.

**Comment by susam** [comment]
@shymega Thanks for making the changes. The changes are now available in version 0.2.0.

**Pull request merged**
